import 'package:niskala_model_gen/src/models/openapi/schema_model.dart';

/// Internal class used to track models that need to be generated by the generator loop.
class PendingModel {
  PendingModel({
    required this.className,
    required this.schema,
    required this.subFolder,
    this.components,
  });

  final String className;
  final SchemaModel schema;
  final Map<String, SchemaModel>? components;
  final String subFolder;
}
